name: run-tests

on: [push, pull_request, workflow_dispatch]

env:
  URL: ${{ secrets.URL }}
  IDENTIFIER: ${{ secrets.IDENTIFIER }}
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  run-all-tests:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - name: Checkout to github repository
        uses: actions/checkout@v2

      - name: Setup Python version ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install requirements
        run: pip install -r requirements.txt
